//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ.
    /// </summary>
    // *** Start programmer edit section *** (Заказ CustomAttributes)

    // *** End programmer edit section *** (Заказ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказE", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Статус as \'Статус\'",
            "Клиент as \'Клиент\'",
            "Клиент.Фамилия as \'Фамилия\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Клиент.Фамилия",
            "Сотрудник.Фамилия"})]
    [AssociatedDetailViewAttribute("ЗаказE", "СоставЗаказа", "СоставЗаказаE", true, "", "Состав заказа", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказE", "Клиент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ЗаказE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ЗаказL", new string[] {
            "КодЗаказа as \'Код заказа\'",
            "Дата as \'Дата\'",
            "Статус as \'Статус\'",
            "Клиент.Фамилия as \'Фамилия\'",
            "Сотрудник.Фамилия as \'Фамилия\'"})]
    public class Заказ : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодЗаказа;
        
        private System.DateTime fДата;
        
        private IIS.Test12.Состояния fСтатус;
        
        private IIS.Test12.Клиент fКлиент;
        
        private IIS.Test12.Сотрудник fСотрудник;
        
        private IIS.Test12.DetailArrayOfСоставЗаказа fСоставЗаказа;
        
        // *** Start programmer edit section *** (Заказ CustomMembers)

        // *** End programmer edit section *** (Заказ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Дата CustomAttributes)

        // *** End programmer edit section *** (Заказ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Дата Get start)

                // *** End programmer edit section *** (Заказ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Заказ.Дата Get end)

                // *** End programmer edit section *** (Заказ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Дата Set start)

                // *** End programmer edit section *** (Заказ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Заказ.Дата Set end)

                // *** End programmer edit section *** (Заказ.Дата Set end)
            }
        }
        
        /// <summary>
        /// КодЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.КодЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.КодЗаказа CustomAttributes)
        public virtual int КодЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get start)
                int result = this.fКодЗаказа;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Get end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set start)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set start)
                this.fКодЗаказа = value;
                // *** Start programmer edit section *** (Заказ.КодЗаказа Set end)

                // *** End programmer edit section *** (Заказ.КодЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Статус CustomAttributes)

        // *** End programmer edit section *** (Заказ.Статус CustomAttributes)
        public virtual IIS.Test12.Состояния Статус
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Статус Get start)

                // *** End programmer edit section *** (Заказ.Статус Get start)
                IIS.Test12.Состояния result = this.fСтатус;
                // *** Start programmer edit section *** (Заказ.Статус Get end)

                // *** End programmer edit section *** (Заказ.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Статус Set start)

                // *** End programmer edit section *** (Заказ.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Заказ.Статус Set end)

                // *** End programmer edit section *** (Заказ.Статус Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Клиент CustomAttributes)

        // *** End programmer edit section *** (Заказ.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Test12.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Клиент Get start)

                // *** End programmer edit section *** (Заказ.Клиент Get start)
                IIS.Test12.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Заказ.Клиент Get end)

                // *** End programmer edit section *** (Заказ.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Клиент Set start)

                // *** End programmer edit section *** (Заказ.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Заказ.Клиент Set end)

                // *** End programmer edit section *** (Заказ.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (Заказ.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Test12.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Get start)

                // *** End programmer edit section *** (Заказ.Сотрудник Get start)
                IIS.Test12.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (Заказ.Сотрудник Get end)

                // *** End programmer edit section *** (Заказ.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.Сотрудник Set start)

                // *** End programmer edit section *** (Заказ.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (Заказ.Сотрудник Set end)

                // *** End programmer edit section *** (Заказ.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Заказ.
        /// </summary>
        // *** Start programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)

        // *** End programmer edit section *** (Заказ.СоставЗаказа CustomAttributes)
        public virtual IIS.Test12.DetailArrayOfСоставЗаказа СоставЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get start)
                if ((this.fСоставЗаказа == null))
                {
                    this.fСоставЗаказа = new IIS.Test12.DetailArrayOfСоставЗаказа(this);
                }
                IIS.Test12.DetailArrayOfСоставЗаказа result = this.fСоставЗаказа;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Get end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set start)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set start)
                this.fСоставЗаказа = value;
                // *** Start programmer edit section *** (Заказ.СоставЗаказа Set end)

                // *** End programmer edit section *** (Заказ.СоставЗаказа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказE", typeof(IIS.Test12.Заказ));
                }
            }
            
            /// <summary>
            /// "ЗаказL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказL", typeof(IIS.Test12.Заказ));
                }
            }
        }
    }
}
