//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оповещения.
    /// </summary>
    // *** Start programmer edit section *** (Оповещения CustomAttributes)

    // *** End programmer edit section *** (Оповещения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОповещенияE", new string[] {
            "Описание as \'Описание\'",
            "МестоВыдачи as \'Место выдачи\'",
            "Заказ as \'Заказ\'",
            "Заказ.КодЗаказа as \'Код заказа\'"}, Hidden=new string[] {
            "Заказ.КодЗаказа"})]
    [MasterViewDefineAttribute("ОповещенияE", "Заказ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодЗаказа")]
    [View("ОповещенияL", new string[] {
            "Описание as \'Описание\'",
            "МестоВыдачи as \'Место выдачи\'",
            "Заказ.КодЗаказа as \'Код заказа\'"})]
    public class Оповещения : ICSSoft.STORMNET.DataObject
    {
        
        private string fОписание;
        
        private IIS.Test12.МестоВыдачи fМестоВыдачи;
        
        private IIS.Test12.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (Оповещения CustomMembers)

        // *** End programmer edit section *** (Оповещения CustomMembers)

        
        /// <summary>
        /// МестоВыдачи.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.МестоВыдачи CustomAttributes)

        // *** End programmer edit section *** (Оповещения.МестоВыдачи CustomAttributes)
        public virtual IIS.Test12.МестоВыдачи МестоВыдачи
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Get start)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Get start)
                IIS.Test12.МестоВыдачи result = this.fМестоВыдачи;
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Get end)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Set start)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Set start)
                this.fМестоВыдачи = value;
                // *** Start programmer edit section *** (Оповещения.МестоВыдачи Set end)

                // *** End programmer edit section *** (Оповещения.МестоВыдачи Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.Описание CustomAttributes)

        // *** End programmer edit section *** (Оповещения.Описание CustomAttributes)
        [StrLen(255)]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.Описание Get start)

                // *** End programmer edit section *** (Оповещения.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Оповещения.Описание Get end)

                // *** End programmer edit section *** (Оповещения.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.Описание Set start)

                // *** End programmer edit section *** (Оповещения.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Оповещения.Описание Set end)

                // *** End programmer edit section *** (Оповещения.Описание Set end)
            }
        }
        
        /// <summary>
        /// Оповещения.
        /// </summary>
        // *** Start programmer edit section *** (Оповещения.Заказ CustomAttributes)

        // *** End programmer edit section *** (Оповещения.Заказ CustomAttributes)
        [PropertyStorage(new string[] {
                "Заказ"})]
        [NotNull()]
        public virtual IIS.Test12.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (Оповещения.Заказ Get start)

                // *** End programmer edit section *** (Оповещения.Заказ Get start)
                IIS.Test12.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (Оповещения.Заказ Get end)

                // *** End programmer edit section *** (Оповещения.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оповещения.Заказ Set start)

                // *** End programmer edit section *** (Оповещения.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (Оповещения.Заказ Set end)

                // *** End programmer edit section *** (Оповещения.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОповещенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОповещенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОповещенияE", typeof(IIS.Test12.Оповещения));
                }
            }
            
            /// <summary>
            /// "ОповещенияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОповещенияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОповещенияL", typeof(IIS.Test12.Оповещения));
                }
            }
        }
    }
}
